### PR TITLE
Entity Categories

### LINKED ISSUE #8: Entity categories are needed
HA 2012.11.0 supports entity categories to clean up the auto generated dashboards.  

Would you welcome a PR to add them?

### PR DESCRIPTION
**Pull request by DTTerastar**
Fixes #8.

I put the one that I think 100% are diagnostic:

image

I feel like the totals could also be diagnostic as well, but not sure.

### CODE REVIEW

**Comment by toreamun** [comment]
Maybe all sensors except Capture should be diagnostics? Thats what I think when I read https://developers.home-assistant.io/blog/2021/10/26/config-entity What do you think?

**Comment by DTTerastar** [comment]
> Maybe all sensors except Capture should be diagnostics? Thats what I think when I read https://developers.home-assistant.io/blog/2021/10/26/config-entity What do you think?

Sure, I can do that.

**Comment by DTTerastar** [comment]
image

**Comment by DTTerastar** [comment]
Thanks!

**Pull request merged**
